### ISSUE TITLE
Please do not publish your code or make it available

### ISSUE THREAD

**Issue by theidexisted** [hexinatgithub/6.824#1]
Please do not publish your code or make it available to current or future 6.824 students. github.com repositories are public by default, so please don't put your code there unless you make the repository private. You may find it convenient to use MIT's GitHub, but be sure to create a private repository.

Refer:
https://pdos.csail.mit.edu/6.824/labs/lab-1.html

**Comment by ShaneHeX** [comment]
为什么是我？

**Comment by prehistoric-penguin** [comment]
因为你长得帅，你的进度最快
